# Devoir 1 : Classification de sentiments de deux façons

Bienvenue à votre premier devoir ! Lorsque vous le soumettez sur ZoneCours, assurez-vous de renommer le fichier avec votre nom comme suit : **"Assignment1_{firstname}_{lastname}.ipynb"**. Soumettez une version du notebook où vous avez fait roulez toutes les cellules et laissez les sorties apparentes. La date de remise est fixée à 23 h 59 le 26 février. Le devoir est noté sur un total de 42 points, avec 2 points boni possibles. Si vous avez travaillé sur une quelconque partie du devoir avec d’autres personnes, veuillez indiquer leurs noms ici :

In [1]:
__author__ = "{Votre nom}"
__collaborators__ = "{leurs noms, si plus qu'un, séparez les par un ; si non, laissez vide}"

Toutes les bibliothèques dont vous aurez besoin sont listées ici. Si certaines bibliothèques qui pourraient sembler pertinentes ont été exclues, c’est intentionnel afin que vous preniez le temps d’écrire vos propres fonctions. Veuillez ne pas modifier cette cellule et abstenez-vous d’ajouter d’autres bibliothèques ailleurs. Vous pouvez utiliser toute fonction que vous jugez utile provenant de ces bibliothèques.

In [1]:
from nltk.corpus import movie_reviews
import string
import re
import random
import math
from collections import Counter
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm.notebook import tqdm
random.seed(202601)
torch.manual_seed(202401)
device = torch.device('cpu')

Nous allons comparer deux types de classificateurs de critiques de films : (1) un classificateur de régression logistique basé sur des N-grammes et (2) un classificateur basé sur un LSTM. La première étape consiste à télécharger les données et à créer nos ensembles d’entraînement et de test. Il y a deux classes de critiques : positives et négatives.

In [2]:
review_classes = movie_reviews.categories()
pos_reviews = [(movie_reviews.raw(fileid), 'pos') for fileid in movie_reviews.fileids(categories=['pos'])]
neg_reviews = [(movie_reviews.raw(fileid), 'neg') for fileid in movie_reviews.fileids(categories=['neg'])]
train_dataset = pos_reviews[:800] + neg_reviews[:800]
test_dataset = pos_reviews[800:] + neg_reviews[800:]

In [3]:
train_dataset[0]

('films adapted from comic books have had plenty of success , whether they\'re about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there\'s never really been a comic book like from hell before . \nfor starters , it was created by alan moore ( and eddie campbell ) , who brought the medium to a whole new level in the mid \'80s with a 12-part series called the watchmen . \nto say moore and campbell thoroughly researched the subject of jack the ripper would be like saying michael jackson is starting to look a little odd . \nthe book ( or " graphic novel , " if you will ) is over 500 pages long and includes nearly 30 more that consist of nothing but footnotes . \nin other words , don\'t dismiss this film because of its source . \nif you can get past the whole comic book thing , you might find another stumbling block in from hell\'s directors , albert and allen hughes . \ngetting the hughes brothers to direct this seems almost as ludicrous as casting carrot top in , well , anything , but riddle me this : who better to direct a film that\'s set in the ghetto and features really violent street crime than the mad geniuses behind menace ii society ? \nthe ghetto in question is , of course , whitechapel in 1888 london\'s east end . \nit\'s a filthy , sooty place where the whores ( called " unfortunates " ) are starting to get a little nervous about this mysterious psychopath who has been carving through their profession with surgical precision . \nwhen the first stiff turns up , copper peter godley ( robbie coltrane , the world is not enough ) calls in inspector frederick abberline ( johnny depp , blow ) to crack the case . \nabberline , a widower , has prophetic dreams he unsuccessfully tries to quell with copious amounts of absinthe and opium . \nupon arriving in whitechapel , he befriends an unfortunate named mary kelly ( heather graham , say it isn\'t so ) and proceeds to investigate the horribly gruesome crimes that even the police surgeon can\'t stomach . \ni don\'t think anyone needs to be briefed on jack the ripper , so i won\'t go into the particulars here , other than to say moore and campbell have a unique and interesting theory about both the identity of the killer and the reasons he chooses to slay . \nin the comic , they don\'t bother cloaking the identity of the ripper , but screenwriters terry hayes ( vertical limit ) and rafael yglesias ( les mis ? rables ) do a good job of keeping him hidden from viewers until the very end . \nit\'s funny to watch the locals blindly point the finger of blame at jews and indians because , after all , an englishman could never be capable of committing such ghastly acts . \nand from hell\'s ending had me whistling the stonecutters song from the simpsons for days ( " who holds back the electric car/who made steve guttenberg a star ? " ) . \ndon\'t worry - it\'ll all make sense when you see it . \nnow onto from hell\'s appearance : it\'s certainly dark and bleak enough , and it\'s surprising to see how much more it looks like a tim burton film than planet of the apes did ( at times , it seems like sleepy hollow 2 ) . \nthe print i saw wasn\'t completely finished ( both color and music had not been finalized , so no comments about marilyn manson ) , but cinematographer peter deming ( don\'t say a word ) ably captures the dreariness of victorian-era london and helped make the flashy killing scenes remind me of the crazy flashbacks in twin peaks , even though the violence in the film pales in comparison to that in the black-and-white comic . \noscar winner martin childs\' ( shakespeare in love ) production design turns the original prague surroundings into one creepy place . \neven the acting in from hell is solid , with the dreamy depp turning in a typically strong performance and deftly handling a british accent . \nians holm ( joe gould\'s secret ) and richardson ( 102 dalmatians ) log in great supporting roles , but the big surprise here is graham . \ni cringed the first time she opened her mouth , imagining her attempt at an irish accent , but it actually wasn\'t half bad . \nthe film , however , is all good . \n2 : 00 - r for strong violence/gore , sexuality , language and drug content \n',
 'pos')

In [4]:
len(train_dataset)

1600

1. **[3 points]** L’étape suivante consiste à tokeniser les critiques. Vous devez maintenant écrire une fonction de prétraitement qui prend une critique et (1) supprime la ponctuation, (2) met tous les mots en minuscules et (3) les sépare en tokens en utilisant tout type d’espacement. Assurez-vous qu’il n’y a pas de tokens vides.

In [5]:
def preprocess(review:str):
    tokenized_review = []
    punctuations = list(string.punctuation)
    ## TO DO
    ### Suppression ponctuation
    punctuationsStr = "".join(punctuations)
    pattern = f"[{re.escape(punctuationsStr)}]+"
    reviewPrepared = re.sub(pattern,'',review)
    ### Cast en minuscules
    reviewPrepared= reviewPrepared.lower()
    ### Séparation en token
    tokenized_review = reviewPrepared.split()

    if "" in tokenized_review:
        raise ValueError("ATTENTION: tokenized_review contient des tokens vides") 

    
    ##
    return tokenized_review

In [6]:
# TODO: à supprimer avant de soumettre
# Pour tester la fonction preprocess:
## échantillon de données d'entraînement déterministique
#preprocess(train_dataset[0][0])

## échantillon de données d'entraînement aléatoire
rndTrainDataIdx = random.randint(0, len(train_dataset)-1)
rndPreprocessData=preprocess(train_dataset[rndTrainDataIdx][0])
rndPreprocessData

['youve',
 'got',
 'mail',
 'works',
 'alot',
 'better',
 'than',
 'it',
 'deserves',
 'to',
 'in',
 'order',
 'to',
 'make',
 'the',
 'film',
 'a',
 'success',
 'all',
 'they',
 'had',
 'to',
 'do',
 'was',
 'cast',
 'two',
 'extremely',
 'popular',
 'and',
 'attractive',
 'stars',
 'have',
 'them',
 'share',
 'the',
 'screen',
 'for',
 'about',
 'two',
 'hours',
 'and',
 'then',
 'collect',
 'the',
 'profits',
 'no',
 'real',
 'acting',
 'was',
 'involved',
 'and',
 'there',
 'is',
 'not',
 'an',
 'original',
 'or',
 'inventive',
 'bone',
 'in',
 'its',
 'body',
 'its',
 'basically',
 'a',
 'complete',
 'reshoot',
 'of',
 'the',
 'shop',
 'around',
 'the',
 'corner',
 'only',
 'adding',
 'a',
 'few',
 'modern',
 'twists',
 'essentially',
 'it',
 'goes',
 'against',
 'and',
 'defies',
 'all',
 'concepts',
 'of',
 'good',
 'contemporary',
 'filmmaking',
 'its',
 'overly',
 'sentimental',
 'and',
 'at',
 'times',
 'terribly',
 'mushy',
 'not',
 'to',
 'mention',
 'very',
 'manipulative',
 'but',
 'oh',
 'how',
 'enjoyable',
 'that',
 'manipulation',
 'is',
 'but',
 'there',
 'must',
 'be',
 'something',
 'other',
 'than',
 'the',
 'casting',
 'and',
 'manipulation',
 'that',
 'makes',
 'the',
 'movie',
 'work',
 'as',
 'well',
 'as',
 'it',
 'does',
 'because',
 'i',
 'absolutely',
 'hated',
 'the',
 'previous',
 'ryanhanks',
 'teaming',
 'sleepless',
 'in',
 'seattle',
 'it',
 'couldnt',
 'have',
 'been',
 'the',
 'directing',
 'because',
 'both',
 'films',
 'were',
 'helmed',
 'by',
 'the',
 'same',
 'woman',
 'i',
 'havent',
 'quite',
 'yet',
 'figured',
 'out',
 'what',
 'i',
 'liked',
 'so',
 'much',
 'about',
 'youve',
 'got',
 'mail',
 'but',
 'then',
 'again',
 'is',
 'that',
 'really',
 'important',
 'if',
 'you',
 'like',
 'something',
 'so',
 'much',
 'why',
 'even',
 'question',
 'it',
 'again',
 'the',
 'storyline',
 'is',
 'as',
 'cliched',
 'as',
 'they',
 'come',
 'tom',
 'hanks',
 'plays',
 'joe',
 'fox',
 'the',
 'insanely',
 'likeable',
 'owner',
 'of',
 'a',
 'discount',
 'book',
 'chain',
 'and',
 'meg',
 'ryan',
 'plays',
 'kathleen',
 'kelley',
 'the',
 'even',
 'more',
 'insanely',
 'likeable',
 'proprietor',
 'of',
 'a',
 'familyrun',
 'childrens',
 'book',
 'shop',
 'called',
 'in',
 'a',
 'nice',
 'homage',
 'the',
 'shop',
 'around',
 'the',
 'corner',
 'fox',
 'and',
 'kelley',
 'soon',
 'become',
 'bitter',
 'rivals',
 'because',
 'the',
 'new',
 'fox',
 'books',
 'store',
 'is',
 'opening',
 'up',
 'right',
 'across',
 'the',
 'block',
 'from',
 'the',
 'small',
 'business',
 'little',
 'do',
 'they',
 'know',
 'they',
 'are',
 'already',
 'in',
 'love',
 'with',
 'each',
 'other',
 'over',
 'the',
 'internet',
 'only',
 'neither',
 'party',
 'knows',
 'the',
 'other',
 'persons',
 'true',
 'identity',
 'the',
 'rest',
 'of',
 'the',
 'story',
 'isnt',
 'important',
 'because',
 'all',
 'it',
 'does',
 'is',
 'serve',
 'as',
 'a',
 'mere',
 'backdrop',
 'for',
 'the',
 'two',
 'stars',
 'to',
 'share',
 'the',
 'screen',
 'sure',
 'there',
 'are',
 'some',
 'mildly',
 'interesting',
 'subplots',
 'but',
 'they',
 'all',
 'fail',
 'in',
 'comparison',
 'to',
 'the',
 'utter',
 'cuteness',
 'of',
 'the',
 'main',
 'relationship',
 'all',
 'of',
 'this',
 'of',
 'course',
 'leads',
 'up',
 'to',
 'the',
 'predictable',
 'climax',
 'but',
 'as',
 'foreseeable',
 'as',
 'the',
 'ending',
 'is',
 'its',
 'so',
 'damn',
 'cute',
 'and',
 'welldone',
 'that',
 'i',
 'doubt',
 'any',
 'movie',
 'in',
 'the',
 'entire',
 'year',
 'contains',
 'a',
 'scene',
 'the',
 'evokes',
 'as',
 'much',
 'pure',
 'joy',
 'as',
 'this',
 'part',
 'does',
 'when',
 'ryan',
 'discovers',
 'the',
 'true',
 'identity',
 'of',
 'her',
 'online',
 'love',
 'i',
 'was',
 'filled',
 'with',
 'such',
 'for',
 'lack',
 'of',
 'a',
 'better',
 'word',
 'happiness',
 'that',
 'for',
 'the',
 'first',
 'time',
 'all',
 'year',
 'i',
 'actually',
 'left',
 'the',
 'theater',
 'smiling']

## Classificateur 1 : Caractéristiques N‑grammes et régression logistique

Ce premier classificateur extrait des caractéristiques de type N‑grammes à partir des critiques, les transforme en vecteurs, puis entraîne un classificateur basé sur une régression logistique à partir de ces caractéristiques.

2. **[3 points]** Écrivez une fonction utilitaire qui retourne un vocabulaire de N‑grammes, *ngram_vocab*, pour toute valeur de *n* ≥ 1, étant donné un jeu de données *tokenized_reviews* étiquetées (une liste de tuples *(tokenized_review, review_class)*). Il est important que la taille du vocabulaire soit limitée à la taille maximale *max_vocab_size*. *ngram_vocab* doit inclure les *max_vocab_size* N‑grams les plus fréquents sur l’ensemble des critiques. Le type de retour doit être une liste de tuples, où chaque tuple représente un N‑gramme.

In [7]:
def get_ngram_tokenized(tokenized_review:list, n:int) -> list[tuple]:
    """
    Fonction qui construit un token de N-grammes à partir d'un token de mots.
    Args:
        tokenized_review : list 
            Token de mots d'une critique.
        n : int
            La taille des N-grammes à construire.
    """
    grams = [tokenized_review[i:] for i in range(n)]
    return list(zip(*grams))

In [8]:
# TODO: à supprimer avant de soumettre
# Pour tester la fonction get_ngram_tokenized
get_ngram_tokenized(['this', 'is', 'a', 'test'], 3)
get_ngram_tokenized(rndPreprocessData, 10)

[('youve',
  'got',
  'mail',
  'works',
  'alot',
  'better',
  'than',
  'it',
  'deserves',
  'to'),
 ('got',
  'mail',
  'works',
  'alot',
  'better',
  'than',
  'it',
  'deserves',
  'to',
  'in'),
 ('mail',
  'works',
  'alot',
  'better',
  'than',
  'it',
  'deserves',
  'to',
  'in',
  'order'),
 ('works',
  'alot',
  'better',
  'than',
  'it',
  'deserves',
  'to',
  'in',
  'order',
  'to'),
 ('alot',
  'better',
  'than',
  'it',
  'deserves',
  'to',
  'in',
  'order',
  'to',
  'make'),
 ('better',
  'than',
  'it',
  'deserves',
  'to',
  'in',
  'order',
  'to',
  'make',
  'the'),
 ('than', 'it', 'deserves', 'to', 'in', 'order', 'to', 'make', 'the', 'film'),
 ('it', 'deserves', 'to', 'in', 'order', 'to', 'make', 'the', 'film', 'a'),
 ('deserves',
  'to',
  'in',
  'order',
  'to',
  'make',
  'the',
  'film',
  'a',
  'success'),
 ('to', 'in', 'order', 'to', 'make', 'the', 'film', 'a', 'success', 'all'),
 ('in', 'order', 'to', 'make', 'the', 'film', 'a', 'success', 'all', 'they'),
 ('order', 'to', 'make', 'the', 'film', 'a', 'success', 'all', 'they', 'had'),
 ('to', 'make', 'the', 'film', 'a', 'success', 'all', 'they', 'had', 'to'),
 ('make', 'the', 'film', 'a', 'success', 'all', 'they', 'had', 'to', 'do'),
 ('the', 'film', 'a', 'success', 'all', 'they', 'had', 'to', 'do', 'was'),
 ('film', 'a', 'success', 'all', 'they', 'had', 'to', 'do', 'was', 'cast'),
 ('a', 'success', 'all', 'they', 'had', 'to', 'do', 'was', 'cast', 'two'),
 ('success',
  'all',
  'they',
  'had',
  'to',
  'do',
  'was',
  'cast',
  'two',
  'extremely'),
 ('all',
  'they',
  'had',
  'to',
  'do',
  'was',
  'cast',
  'two',
  'extremely',
  'popular'),
 ('they',
  'had',
  'to',
  'do',
  'was',
  'cast',
  'two',
  'extremely',
  'popular',
  'and'),
 ('had',
  'to',
  'do',
  'was',
  'cast',
  'two',
  'extremely',
  'popular',
  'and',
  'attractive'),
 ('to',
  'do',
  'was',
  'cast',
  'two',
  'extremely',
  'popular',
  'and',
  'attractive',
  'stars'),
 ('do',
  'was',
  'cast',
  'two',
  'extremely',
  'popular',
  'and',
  'attractive',
  'stars',
  'have'),
 ('was',
  'cast',
  'two',
  'extremely',
  'popular',
  'and',
  'attractive',
  'stars',
  'have',
  'them'),
 ('cast',
  'two',
  'extremely',
  'popular',
  'and',
  'attractive',
  'stars',
  'have',
  'them',
  'share'),
 ('two',
  'extremely',
  'popular',
  'and',
  'attractive',
  'stars',
  'have',
  'them',
  'share',
  'the'),
 ('extremely',
  'popular',
  'and',
  'attractive',
  'stars',
  'have',
  'them',
  'share',
  'the',
  'screen'),
 ('popular',
  'and',
  'attractive',
  'stars',
  'have',
  'them',
  'share',
  'the',
  'screen',
  'for'),
 ('and',
  'attractive',
  'stars',
  'have',
  'them',
  'share',
  'the',
  'screen',
  'for',
  'about'),
 ('attractive',
  'stars',
  'have',
  'them',
  'share',
  'the',
  'screen',
  'for',
  'about',
  'two'),
 ('stars',
  'have',
  'them',
  'share',
  'the',
  'screen',
  'for',
  'about',
  'two',
  'hours'),
 ('have',
  'them',
  'share',
  'the',
  'screen',
  'for',
  'about',
  'two',
  'hours',
  'and'),
 ('them',
  'share',
  'the',
  'screen',
  'for',
  'about',
  'two',
  'hours',
  'and',
  'then'),
 ('share',
  'the',
  'screen',
  'for',
  'about',
  'two',
  'hours',
  'and',
  'then',
  'collect'),
 ('the',
  'screen',
  'for',
  'about',
  'two',
  'hours',
  'and',
  'then',
  'collect',
  'the'),
 ('screen',
  'for',
  'about',
  'two',
  'hours',
  'and',
  'then',
  'collect',
  'the',
  'profits'),
 ('for',
  'about',
  'two',
  'hours',
  'and',
  'then',
  'collect',
  'the',
  'profits',
  'no'),
 ('about',
  'two',
  'hours',
  'and',
  'then',
  'collect',
  'the',
  'profits',
  'no',
  'real'),
 ('two',
  'hours',
  'and',
  'then',
  'collect',
  'the',
  'profits',
  'no',
  'real',
  'acting'),
 ('hours',
  'and',
  'then',
  'collect',
  'the',
  'profits',
  'no',
  'real',
  'acting',
  'was'),
 ('and',
  'then',
  'collect',
  'the',
  'profits',
  'no',
  'real',
  'acting',
  'was',
  'involved'),
 ('then',
  'collect',
  'the',
  'profits',
  'no',
  'real',
  'acting',
  'was',
  'involved',
  'and'),
 ('collect',
  'the',
  'profits',
  'no',
  'real',
  'acting',
  'was',
  'involved',
  'and',
  'there'),
 ('the',
  'profits',
  'no',
  'real',
  'acting',
  'was',
  'involved',
  'and',
  'there',
  'is'),
 ('profits',
  'no',
  'real',
  'acting',
  'was',
  'involved',
  'and',
  'there',
  'is',
  'not'),
 ('no',
  'real',
  'acting',
  'was',
  'involved',
  'and',
  'there',
  'is',
  'not',
  'an'),
 ('real',
  'acting',
  'was',
  'involved',
  'and',
  'there',
  'is',
  'not',
  'an',
  'original'),
 ('acting',
  'was',
  'involved',
  'and',
  'there',
  'is',
  'not',
  'an',
  'original',
  'or'),
 ('was',
  'involved',
  'and',
  'there',
  'is',
  'not',
  'an',
  'original',
  'or',
  'inventive'),
 ('involved',
  'and',
  'there',
  'is',
  'not',
  'an',
  'original',
  'or',
  'inventive',
  'bone'),
 ('and',
  'there',
  'is',
  'not',
  'an',
  'original',
  'or',
  'inventive',
  'bone',
  'in'),
 ('there',
  'is',
  'not',
  'an',
  'original',
  'or',
  'inventive',
  'bone',
  'in',
  'its'),
 ('is',
  'not',
  'an',
  'original',
  'or',
  'inventive',
  'bone',
  'in',
  'its',
  'body'),
 ('not',
  'an',
  'original',
  'or',
  'inventive',
  'bone',
  'in',
  'its',
  'body',
  'its'),
 ('an',
  'original',
  'or',
  'inventive',
  'bone',
  'in',
  'its',
  'body',
  'its',
  'basically'),
 ('original',
  'or',
  'inventive',
  'bone',
  'in',
  'its',
  'body',
  'its',
  'basically',
  'a'),
 ('or',
  'inventive',
  'bone',
  'in',
  'its',
  'body',
  'its',
  'basically',
  'a',
  'complete'),
 ('inventive',
  'bone',
  'in',
  'its',
  'body',
  'its',
  'basically',
  'a',
  'complete',
  'reshoot'),
 ('bone',
  'in',
  'its',
  'body',
  'its',
  'basically',
  'a',
  'complete',
  'reshoot',
  'of'),
 ('in',
  'its',
  'body',
  'its',
  'basically',
  'a',
  'complete',
  'reshoot',
  'of',
  'the'),
 ('its',
  'body',
  'its',
  'basically',
  'a',
  'complete',
  'reshoot',
  'of',
  'the',
  'shop'),
 ('body',
  'its',
  'basically',
  'a',
  'complete',
  'reshoot',
  'of',
  'the',
  'shop',
  'around'),
 ('its',
  'basically',
  'a',
  'complete',
  'reshoot',
  'of',
  'the',
  'shop',
  'around',
  'the'),
 ('basically',
  'a',
  'complete',
  'reshoot',
  'of',
  'the',
  'shop',
  'around',
  'the',
  'corner'),
 ('a',
  'complete',
  'reshoot',
  'of',
  'the',
  'shop',
  'around',
  'the',
  'corner',
  'only'),
 ('complete',
  'reshoot',
  'of',
  'the',
  'shop',
  'around',
  'the',
  'corner',
  'only',
  'adding'),
 ('reshoot',
  'of',
  'the',
  'shop',
  'around',
  'the',
  'corner',
  'only',
  'adding',
  'a'),
 ('of',
  'the',
  'shop',
  'around',
  'the',
  'corner',
  'only',
  'adding',
  'a',
  'few'),
 ('the',
  'shop',
  'around',
  'the',
  'corner',
  'only',
  'adding',
  'a',
  'few',
  'modern'),
 ('shop',
  'around',
  'the',
  'corner',
  'only',
  'adding',
  'a',
  'few',
  'modern',
  'twists'),
 ('around',
  'the',
  'corner',
  'only',
  'adding',
  'a',
  'few',
  'modern',
  'twists',
  'essentially'),
 ('the',
  'corner',
  'only',
  'adding',
  'a',
  'few',
  'modern',
  'twists',
  'essentially',
  'it'),
 ('corner',
  'only',
  'adding',
  'a',
  'few',
  'modern',
  'twists',
  'essentially',
  'it',
  'goes'),
 ('only',
  'adding',
  'a',
  'few',
  'modern',
  'twists',
  'essentially',
  'it',
  'goes',
  'against'),
 ('adding',
  'a',
  'few',
  'modern',
  'twists',
  'essentially',
  'it',
  'goes',
  'against',
  'and'),
 ('a',
  'few',
  'modern',
  'twists',
  'essentially',
  'it',
  'goes',
  'against',
  'and',
  'defies'),
 ('few',
  'modern',
  'twists',
  'essentially',
  'it',
  'goes',
  'against',
  'and',
  'defies',
  'all'),
 ('modern',
  'twists',
  'essentially',
  'it',
  'goes',
  'against',
  'and',
  'defies',
  'all',
  'concepts'),
 ('twists',
  'essentially',
  'it',
  'goes',
  'against',
  'and',
  'defies',
  'all',
  'concepts',
  'of'),
 ('essentially',
  'it',
  'goes',
  'against',
  'and',
  'defies',
  'all',
  'concepts',
  'of',
  'good'),
 ('it',
  'goes',
  'against',
  'and',
  'defies',
  'all',
  'concepts',
  'of',
  'good',
  'contemporary'),
 ('goes',
  'against',
  'and',
  'defies',
  'all',
  'concepts',
  'of',
  'good',
  'contemporary',
  'filmmaking'),
 ('against',
  'and',
  'defies',
  'all',
  'concepts',
  'of',
  'good',
  'contemporary',
  'filmmaking',
  'its'),
 ('and',
  'defies',
  'all',
  'concepts',
  'of',
  'good',
  'contemporary',
  'filmmaking',
  'its',
  'overly'),
 ('defies',
  'all',
  'concepts',
  'of',
  'good',
  'contemporary',
  'filmmaking',
  'its',
  'overly',
  'sentimental'),
 ('all',
  'concepts',
  'of',
  'good',
  'contemporary',
  'filmmaking',
  'its',
  'overly',
  'sentimental',
  'and'),
 ('concepts',
  'of',
  'good',
  'contemporary',
  'filmmaking',
  'its',
  'overly',
  'sentimental',
  'and',
  'at'),
 ('of',
  'good',
  'contemporary',
  'filmmaking',
  'its',
  'overly',
  'sentimental',
  'and',
  'at',
  'times'),
 ('good',
  'contemporary',
  'filmmaking',
  'its',
  'overly',
  'sentimental',
  'and',
  'at',
  'times',
  'terribly'),
 ('contemporary',
  'filmmaking',
  'its',
  'overly',
  'sentimental',
  'and',
  'at',
  'times',
  'terribly',
  'mushy'),
 ('filmmaking',
  'its',
  'overly',
  'sentimental',
  'and',
  'at',
  'times',
  'terribly',
  'mushy',
  'not'),
 ('its',
  'overly',
  'sentimental',
  'and',
  'at',
  'times',
  'terribly',
  'mushy',
  'not',
  'to'),
 ('overly',
  'sentimental',
  'and',
  'at',
  'times',
  'terribly',
  'mushy',
  'not',
  'to',
  'mention'),
 ('sentimental',
  'and',
  'at',
  'times',
  'terribly',
  'mushy',
  'not',
  'to',
  'mention',
  'very'),
 ('and',
  'at',
  'times',
  'terribly',
  'mushy',
  'not',
  'to',
  'mention',
  'very',
  'manipulative'),
 ('at',
  'times',
  'terribly',
  'mushy',
  'not',
  'to',
  'mention',
  'very',
  'manipulative',
  'but'),
 ('times',
  'terribly',
  'mushy',
  'not',
  'to',
  'mention',
  'very',
  'manipulative',
  'but',
  'oh'),
 ('terribly',
  'mushy',
  'not',
  'to',
  'mention',
  'very',
  'manipulative',
  'but',
  'oh',
  'how'),
 ('mushy',
  'not',
  'to',
  'mention',
  'very',
  'manipulative',
  'but',
  'oh',
  'how',
  'enjoyable'),
 ('not',
  'to',
  'mention',
  'very',
  'manipulative',
  'but',
  'oh',
  'how',
  'enjoyable',
  'that'),
 ('to',
  'mention',
  'very',
  'manipulative',
  'but',
  'oh',
  'how',
  'enjoyable',
  'that',
  'manipulation'),
 ('mention',
  'very',
  'manipulative',
  'but',
  'oh',
  'how',
  'enjoyable',
  'that',
  'manipulation',
  'is'),
 ('very',
  'manipulative',
  'but',
  'oh',
  'how',
  'enjoyable',
  'that',
  'manipulation',
  'is',
  'but'),
 ('manipulative',
  'but',
  'oh',
  'how',
  'enjoyable',
  'that',
  'manipulation',
  'is',
  'but',
  'there'),
 ('but',
  'oh',
  'how',
  'enjoyable',
  'that',
  'manipulation',
  'is',
  'but',
  'there',
  'must'),
 ('oh',
  'how',
  'enjoyable',
  'that',
  'manipulation',
  'is',
  'but',
  'there',
  'must',
  'be'),
 ('how',
  'enjoyable',
  'that',
  'manipulation',
  'is',
  'but',
  'there',
  'must',
  'be',
  'something'),
 ('enjoyable',
  'that',
  'manipulation',
  'is',
  'but',
  'there',
  'must',
  'be',
  'something',
  'other'),
 ('that',
  'manipulation',
  'is',
  'but',
  'there',
  'must',
  'be',
  'something',
  'other',
  'than'),
 ('manipulation',
  'is',
  'but',
  'there',
  'must',
  'be',
  'something',
  'other',
  'than',
  'the'),
 ('is',
  'but',
  'there',
  'must',
  'be',
  'something',
  'other',
  'than',
  'the',
  'casting'),
 ('but',
  'there',
  'must',
  'be',
  'something',
  'other',
  'than',
  'the',
  'casting',
  'and'),
 ('there',
  'must',
  'be',
  'something',
  'other',
  'than',
  'the',
  'casting',
  'and',
  'manipulation'),
 ('must',
  'be',
  'something',
  'other',
  'than',
  'the',
  'casting',
  'and',
  'manipulation',
  'that'),
 ('be',
  'something',
  'other',
  'than',
  'the',
  'casting',
  'and',
  'manipulation',
  'that',
  'makes'),
 ('something',
  'other',
  'than',
  'the',
  'casting',
  'and',
  'manipulation',
  'that',
  'makes',
  'the'),
 ('other',
  'than',
  'the',
  'casting',
  'and',
  'manipulation',
  'that',
  'makes',
  'the',
  'movie'),
 ('than',
  'the',
  'casting',
  'and',
  'manipulation',
  'that',
  'makes',
  'the',
  'movie',
  'work'),
 ('the',
  'casting',
  'and',
  'manipulation',
  'that',
  'makes',
  'the',
  'movie',
  'work',
  'as'),
 ('casting',
  'and',
  'manipulation',
  'that',
  'makes',
  'the',
  'movie',
  'work',
  'as',
  'well'),
 ('and',
  'manipulation',
  'that',
  'makes',
  'the',
  'movie',
  'work',
  'as',
  'well',
  'as'),
 ('manipulation',
  'that',
  'makes',
  'the',
  'movie',
  'work',
  'as',
  'well',
  'as',
  'it'),
 ('that', 'makes', 'the', 'movie', 'work', 'as', 'well', 'as', 'it', 'does'),
 ('makes',
  'the',
  'movie',
  'work',
  'as',
  'well',
  'as',
  'it',
  'does',
  'because'),
 ('the', 'movie', 'work', 'as', 'well', 'as', 'it', 'does', 'because', 'i'),
 ('movie',
  'work',
  'as',
  'well',
  'as',
  'it',
  'does',
  'because',
  'i',
  'absolutely'),
 ('work',
  'as',
  'well',
  'as',
  'it',
  'does',
  'because',
  'i',
  'absolutely',
  'hated'),
 ('as',
  'well',
  'as',
  'it',
  'does',
  'because',
  'i',
  'absolutely',
  'hated',
  'the'),
 ('well',
  'as',
  'it',
  'does',
  'because',
  'i',
  'absolutely',
  'hated',
  'the',
  'previous'),
 ('as',
  'it',
  'does',
  'because',
  'i',
  'absolutely',
  'hated',
  'the',
  'previous',
  'ryanhanks'),
 ('it',
  'does',
  'because',
  'i',
  'absolutely',
  'hated',
  'the',
  'previous',
  'ryanhanks',
  'teaming'),
 ('does',
  'because',
  'i',
  'absolutely',
  'hated',
  'the',
  'previous',
  'ryanhanks',
  'teaming',
  'sleepless'),
 ('because',
  'i',
  'absolutely',
  'hated',
  'the',
  'previous',
  'ryanhanks',
  'teaming',
  'sleepless',
  'in'),
 ('i',
  'absolutely',
  'hated',
  'the',
  'previous',
  'ryanhanks',
  'teaming',
  'sleepless',
  'in',
  'seattle'),
 ('absolutely',
  'hated',
  'the',
  'previous',
  'ryanhanks',
  'teaming',
  'sleepless',
  'in',
  'seattle',
  'it'),
 ('hated',
  'the',
  'previous',
  'ryanhanks',
  'teaming',
  'sleepless',
  'in',
  'seattle',
  'it',
  'couldnt'),
 ('the',
  'previous',
  'ryanhanks',
  'teaming',
  'sleepless',
  'in',
  'seattle',
  'it',
  'couldnt',
  'have'),
 ('previous',
  'ryanhanks',
  'teaming',
  'sleepless',
  'in',
  'seattle',
  'it',
  'couldnt',
  'have',
  'been'),
 ('ryanhanks',
  'teaming',
  'sleepless',
  'in',
  'seattle',
  'it',
  'couldnt',
  'have',
  'been',
  'the'),
 ('teaming',
  'sleepless',
  'in',
  'seattle',
  'it',
  'couldnt',
  'have',
  'been',
  'the',
  'directing'),
 ('sleepless',
  'in',
  'seattle',
  'it',
  'couldnt',
  'have',
  'been',
  'the',
  'directing',
  'because'),
 ('in',
  'seattle',
  'it',
  'couldnt',
  'have',
  'been',
  'the',
  'directing',
  'because',
  'both'),
 ('seattle',
  'it',
  'couldnt',
  'have',
  'been',
  'the',
  'directing',
  'because',
  'both',
  'films'),
 ('it',
  'couldnt',
  'have',
  'been',
  'the',
  'directing',
  'because',
  'both',
  'films',
  'were'),
 ('couldnt',
  'have',
  'been',
  'the',
  'directing',
  'because',
  'both',
  'films',
  'were',
  'helmed'),
 ('have',
  'been',
  'the',
  'directing',
  'because',
  'both',
  'films',
  'were',
  'helmed',
  'by'),
 ('been',
  'the',
  'directing',
  'because',
  'both',
  'films',
  'were',
  'helmed',
  'by',
  'the'),
 ('the',
  'directing',
  'because',
  'both',
  'films',
  'were',
  'helmed',
  'by',
  'the',
  'same'),
 ('directing',
  'because',
  'both',
  'films',
  'were',
  'helmed',
  'by',
  'the',
  'same',
  'woman'),
 ('because',
  'both',
  'films',
  'were',
  'helmed',
  'by',
  'the',
  'same',
  'woman',
  'i'),
 ('both',
  'films',
  'were',
  'helmed',
  'by',
  'the',
  'same',
  'woman',
  'i',
  'havent'),
 ('films',
  'were',
  'helmed',
  'by',
  'the',
  'same',
  'woman',
  'i',
  'havent',
  'quite'),
 ('were',
  'helmed',
  'by',
  'the',
  'same',
  'woman',
  'i',
  'havent',
  'quite',
  'yet'),
 ('helmed',
  'by',
  'the',
  'same',
  'woman',
  'i',
  'havent',
  'quite',
  'yet',
  'figured'),
 ('by',
  'the',
  'same',
  'woman',
  'i',
  'havent',
  'quite',
  'yet',
  'figured',
  'out'),
 ('the',
  'same',
  'woman',
  'i',
  'havent',
  'quite',
  'yet',
  'figured',
  'out',
  'what'),
 ('same',
  'woman',
  'i',
  'havent',
  'quite',
  'yet',
  'figured',
  'out',
  'what',
  'i'),
 ('woman',
  'i',
  'havent',
  'quite',
  'yet',
  'figured',
  'out',
  'what',
  'i',
  'liked'),
 ('i', 'havent', 'quite', 'yet', 'figured', 'out', 'what', 'i', 'liked', 'so'),
 ('havent',
  'quite',
  'yet',
  'figured',
  'out',
  'what',
  'i',
  'liked',
  'so',
  'much'),
 ('quite',
  'yet',
  'figured',
  'out',
  'what',
  'i',
  'liked',
  'so',
  'much',
  'about'),
 ('yet',
  'figured',
  'out',
  'what',
  'i',
  'liked',
  'so',
  'much',
  'about',
  'youve'),
 ('figured',
  'out',
  'what',
  'i',
  'liked',
  'so',
  'much',
  'about',
  'youve',
  'got'),
 ('out', 'what', 'i', 'liked', 'so', 'much', 'about', 'youve', 'got', 'mail'),
 ('what', 'i', 'liked', 'so', 'much', 'about', 'youve', 'got', 'mail', 'but'),
 ('i', 'liked', 'so', 'much', 'about', 'youve', 'got', 'mail', 'but', 'then'),
 ('liked',
  'so',
  'much',
  'about',
  'youve',
  'got',
  'mail',
  'but',
  'then',
  'again'),
 ('so', 'much', 'about', 'youve', 'got', 'mail', 'but', 'then', 'again', 'is'),
 ('much',
  'about',
  'youve',
  'got',
  'mail',
  'but',
  'then',
  'again',
  'is',
  'that'),
 ('about',
  'youve',
  'got',
  'mail',
  'but',
  'then',
  'again',
  'is',
  'that',
  'really'),
 ('youve',
  'got',
  'mail',
  'but',
  'then',
  'again',
  'is',
  'that',
  'really',
  'important'),
 ('got',
  'mail',
  'but',
  'then',
  'again',
  'is',
  'that',
  'really',
  'important',
  'if'),
 ('mail',
  'but',
  'then',
  'again',
  'is',
  'that',
  'really',
  'important',
  'if',
  'you'),
 ('but',
  'then',
  'again',
  'is',
  'that',
  'really',
  'important',
  'if',
  'you',
  'like'),
 ('then',
  'again',
  'is',
  'that',
  'really',
  'important',
  'if',
  'you',
  'like',
  'something'),
 ('again',
  'is',
  'that',
  'really',
  'important',
  'if',
  'you',
  'like',
  'something',
  'so'),
 ('is',
  'that',
  'really',
  'important',
  'if',
  'you',
  'like',
  'something',
  'so',
  'much'),
 ('that',
  'really',
  'important',
  'if',
  'you',
  'like',
  'something',
  'so',
  'much',
  'why'),
 ('really',
  'important',
  'if',
  'you',
  'like',
  'something',
  'so',
  'much',
  'why',
  'even'),
 ('important',
  'if',
  'you',
  'like',
  'something',
  'so',
  'much',
  'why',
  'even',
  'question'),
 ('if',
  'you',
  'like',
  'something',
  'so',
  'much',
  'why',
  'even',
  'question',
  'it'),
 ('you',
  'like',
  'something',
  'so',
  'much',
  'why',
  'even',
  'question',
  'it',
  'again'),
 ('like',
  'something',
  'so',
  'much',
  'why',
  'even',
  'question',
  'it',
  'again',
  'the'),
 ('something',
  'so',
  'much',
  'why',
  'even',
  'question',
  'it',
  'again',
  'the',
  'storyline'),
 ('so',
  'much',
  'why',
  'even',
  'question',
  'it',
  'again',
  'the',
  'storyline',
  'is'),
 ('much',
  'why',
  'even',
  'question',
  'it',
  'again',
  'the',
  'storyline',
  'is',
  'as'),
 ('why',
  'even',
  'question',
  'it',
  'again',
  'the',
  'storyline',
  'is',
  'as',
  'cliched'),
 ('even',
  'question',
  'it',
  'again',
  'the',
  'storyline',
  'is',
  'as',
  'cliched',
  'as'),
 ('question',
  'it',
  'again',
  'the',
  'storyline',
  'is',
  'as',
  'cliched',
  'as',
  'they'),
 ('it',
  'again',
  'the',

In [9]:
def get_ngram_vocabulary_maxsize(tokenized_reviews:list[tuple[list[str], str]], n:int, max_vocab_size:int):
    ngram_vocab = []
    ## TO DO
    ### 1) Construire token N-grammes par critique
    ngrams_tokenized_reviews = []
    for review, _ in tokenized_reviews:
        ngrams_tokenized_reviews.extend(get_ngram_tokenized(review, n))
    ### 2) Faire le compte des N-grammes sur l'ensemble des critiques
    ngramsTokenizedReviewsCounter = Counter(ngrams_tokenized_reviews)
    ### 3) Le Top-N définit le nouveau vocabulaire.
    ngramsTokenizedReviewsCounter = ngramsTokenizedReviewsCounter.most_common(max_vocab_size)
    ngram_vocab = list(list(zip(*ngramsTokenizedReviewsCounter))[0])

    
    ##
    return ngram_vocab

In [10]:
# TODO: à supprimer avant de soumettre
# Pour tester la fonction get_ngram_vocabulary_maxsize
tokenized_reviews = [(preprocess(review), label) for review, label in train_dataset]
get_ngram_vocabulary_maxsize(tokenized_reviews, 3, 50)

[('one', 'of', 'the'),
 ('of', 'the', 'film'),
 ('in', 'the', 'film'),
 ('the', 'film', 'is'),
 ('a', 'lot', 'of'),
 ('some', 'of', 'the'),
 ('the', 'rest', 'of'),
 ('to', 'be', 'a'),
 ('of', 'the', 'movie'),
 ('the', 'fact', 'that'),
 ('in', 'this', 'film'),
 ('this', 'is', 'a'),
 ('rest', 'of', 'the'),
 ('most', 'of', 'the'),
 ('this', 'film', 'is'),
 ('is', 'one', 'of'),
 ('the', 'movie', 'is'),
 ('of', 'the', 'most'),
 ('in', 'the', 'movie'),
 ('the', 'end', 'of'),
 ('out', 'of', 'the'),
 ('in', 'order', 'to'),
 ('seems', 'to', 'be'),
 ('as', 'well', 'as'),
 ('this', 'is', 'the'),
 ('could', 'have', 'been'),
 ('it', 'is', 'a'),
 ('there', 'is', 'a'),
 ('a', 'couple', 'of'),
 ('of', 'the', 'best'),
 ('in', 'this', 'movie'),
 ('to', 'be', 'the'),
 ('part', 'of', 'the'),
 ('supposed', 'to', 'be'),
 ('end', 'of', 'the'),
 ('all', 'of', 'the'),
 ('at', 'the', 'end'),
 ('a', 'group', 'of'),
 ('one', 'of', 'those'),
 ('the', 'story', 'is'),
 ('there', 'is', 'no'),
 ('in', 'the', 'end'),
 ('a', 'film', 'that'),
 ('in', 'the', 'first'),
 ('is', 'not', 'a'),
 ('this', 'movie', 'is'),
 ('the', 'story', 'of'),
 ('of', 'this', 'film'),
 ('on', 'the', 'other'),
 ('of', 'the', 'characters')]

3. **[4 points]** Écrivez une fonction utilitaire qui prend un vocabulaire de N‑grammes, *ngram_vocab*, ainsi qu’une critique tokenisée, *tokenized_review*, et qui retourne une représentation vectorisée des comptes de N‑grammes dans la critique. Le type de retour doit être un torch tensor de float, où chaque indice correspond à un N‑gramme dans *ngram_vocab* et où les valeurs correspondent à leurs comptes respectifs.

In [11]:
def get_vectorized_review(tokenized_review:list[str], ngram_vocab:list[tuple]):
    vectorized_review = torch.Tensor([0.0])
    ## TO DO
    ngram_size = len(ngram_vocab[0])
    ### Construire token N-grammes de la critique
    review_ngrams = get_ngram_tokenized(tokenized_review, ngram_size)
    ### Compter les N-grammes de la critique 
    review_ngramsCounter = Counter(review_ngrams)

    vectorized_review = torch.zeros(len(ngram_vocab), dtype=torch.float)
    for i, ngram in enumerate(ngram_vocab):
        if ngram in review_ngramsCounter:
            vectorized_review[i] = review_ngramsCounter[ngram]

    
    ##
    return vectorized_review

In [12]:
# TODO: à supprimer avant de soumettre
# Pour tester la fonction get_vectorized_review
get_vectorized_review(rndPreprocessData, get_ngram_vocabulary_maxsize(tokenized_reviews, 2, 20))

tensor([3., 1., 1., 0., 2., 0., 0., 1., 0., 0., 3., 1., 2., 0., 1., 0., 0., 1.,
        0., 0.])

4. **[4 points]** Écrivez une classe *NgramReviewDataset* qui implémente un objet *torch Dataset*. Elle doit prendre comme input *tokenized_reviews* (une liste de tuples *(tokenized_review, review_class)*) ainsi qu’un vocabulaire de N‑grammes, *ngram_vocab*. Votre fonction d’initialisation doit vectoriser toutes les critiques, de sorte que *self.vectorized_reviews* soit un torch tensor (ou une matrice) de taille |tokenized_reviews| × |ngram_vocab|. Quant à *self.labels*, il doit s’agir d’un torch tensor de taille |tokenized_reviews| × |review_classes|, où chaque élément est un vecteur one‑hot tel que [1,0] correspond à la classe « neg » et [0,1] à la classe « pos ».

In [13]:
class NgramReviewDataset(Dataset):
    def __init__(self, tokenized_reviews:list[tuple[list[str], str]], ngram_vocab:list[tuple]):
        vectorized_reviews = [] 
        labels = [] 
        ## TO DO
        for review, label in tokenized_reviews:
            vectorized_reviews.append(get_vectorized_review(review, ngram_vocab))
            labels.append(0 if label == 'neg' else 1)
        
        ##
        self.vectorized_reviews = torch.stack(vectorized_reviews, dim=0)
        self.labels = F.one_hot(torch.Tensor(labels).long()).float()
        self.length = len(labels)

    def __getitem__(self, index):
        ## TO DO
        vectorized_review = self.vectorized_reviews[index]
        label = self.labels[index]       
        
        ##
        return vectorized_review, label, index

    def __len__(self):
        return self.length

5. **[2 points]** Écrivez une fonction *get_ngram_dataloader* qui prend en entrée *tokenized_reviews*, *ngram_vocab*, une taille de lot *batch_size* et un hyperparamètre *shuffle*. Elle doit utiliser la classe *NgramReviewDataset* définie précédemment et retourner un objet de type *torch.utils.data.DataLoader* qui tient compte des paramètres d’entrée de la fonction.

In [14]:
def get_ngram_dataloader(tokenized_reviews:list[tuple[list[str], str]], ngram_vocab:list[tuple], batch_size:int, shuffle:bool):
    ## TO DO
    data = NgramReviewDataset(tokenized_reviews, ngram_vocab)
    dataloader = DataLoader(data, batch_size=batch_size, shuffle=shuffle)

    
    ##
    return dataloader

#### Régression logistique avec un réseau neuronal à une seule couche linéaire

Voici notre classe de modèle de régression logistique (LR) que nous utiliserons comme base pour nos classificateurs N‑grammes LR.

In [15]:
class LogisticRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        return self.linear(x)

6. **[4 points]** Complétez la fonction *train* que nous utiliserons à la fois pour notre classificateur N‑grammes LR et pour le classificateur basé sur un LSTM. Dans les deux cas, nous effectuons une régression logistique sur un ensemble de caractéristiques variables ; la fonction de perte utilisée dans votre fonction *train* doit donc être choisie en conséquence.

In [16]:
def train(model, dataloader, lr = 0.001, epochs = 5):
    model = model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    model.train()
    for epoch in range(epochs):
        train_loop = tqdm(dataloader, desc=f"Epoch {epoch+1}")
        for i, (batch_inputs, batch_labels, _) in enumerate(train_loop):
            train_loop.set_description(f"Epoch {epoch+1} | Batch {i}")
            ## TO DO
            ### Clear gradients from optimizer
            optimizer.zero_grad()

            ### Forward pass
            outputs = model(batch_inputs)

            ### Compute loss
            loss = nn.CrossEntropyLoss()(outputs, batch_labels.argmax(dim=1))

            ### Backward pass
            loss.backward()

            ### Update parameters
            optimizer.step()

            
            ##
    return model

Entraînons maintenant trois classificateurs N‑grammes en utilisant respectivement des caractéristiques unigrammes, bigrammes et trigrammes.

In [17]:
def train_LR_ngram_classifier(train_dataset:list[tuple[str, str]], review_classes:list[str], n:int, batch_size = 32): 
    tokenized_train = [(preprocess(review), review_class) for review, review_class in  train_dataset]
    ngram_vocab = get_ngram_vocabulary_maxsize(tokenized_train, n, 30000)
    
    train_dataloader = get_ngram_dataloader(tokenized_train, ngram_vocab, batch_size, shuffle=True)

    model = LogisticRegression(len(ngram_vocab), len(review_classes))
    trained_model = train(model, train_dataloader)
    return ngram_vocab, trained_model

In [18]:
unigram_vocab, unigram_model = train_LR_ngram_classifier(train_dataset, review_classes, 1)
bigram_vocab, bigram_model = train_LR_ngram_classifier(train_dataset, review_classes, 2)
trigram_vocab, trigram_model = train_LR_ngram_classifier(train_dataset, review_classes, 3)

Epoch 1:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 2:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 3:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 4:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 5:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 2:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 3:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 4:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 5:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 2:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 3:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 4:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 5:   0%|          | 0/50 [00:00<?, ?it/s]

#### Évaluation de nos classificateurs LR
Voici la fonction d’évaluation pour nos classificateurs. Elle prend le *test_dataset* ainsi qu’un modèle de classification entraîné et retourne les prédictions de classe du modèle pour chaque critique dans les données de test. Elle peut être utilisée pour les deux types de classificateurs présentés dans ce devoir.

In [19]:
def eval(model, dataloader):
    ids = []
    labels = []
    predictions = []
    model.eval()
    with torch.no_grad():
        for batch_inputs, batch_labels, batch_ids in dataloader:
            x = batch_inputs.to(device)
            y_pred = model(x)
            labels += batch_labels.tolist()
            predictions += y_pred.tolist()
            if not isinstance(batch_ids, tuple):
                batch_ids.tolist()
            ids += batch_ids
            
    results = [{'review_id':idx, 'class_label':label, 'prediction': pred} for idx, label, pred in zip(ids, labels, predictions)]
    return results

Évaluons maintenant nos classificateurs N‑grammes sur les données de test.

In [20]:
def eval_LR_ngram_classifier(test_dataset:list[tuple[str, str]], ngram_vocab:list[tuple], model):
    tokenized_test = [(preprocess(review), review_class) for review, review_class in  test_dataset]
    test_dataloader = get_ngram_dataloader(tokenized_test, ngram_vocab, batch_size=32, shuffle=False)
    results = eval(model, test_dataloader)
    return results

In [21]:
unigram_results = eval_LR_ngram_classifier(test_dataset, unigram_vocab, unigram_model)
bigram_results = eval_LR_ngram_classifier(test_dataset, bigram_vocab, bigram_model)
trigram_results = eval_LR_ngram_classifier(test_dataset, trigram_vocab, trigram_model)

#### Résultats

Enfin, comparons les performances relatives de nos classificateurs LR unigramme, bigramme et trigramme.

7. **[4 points]** Écrivez une fonction qui retourne un dictionnaire contenant la précision, le rappel et le score F1 globaux pour toutes les classes, ainsi que l’exactitude (accuracy) globale d’un classificateur.

In [22]:
def get_accuracy_scores(results:list[dict]):
    accuracy = dict([('precision', 0.0),('recall', 0.0), ('f1', 0.0), ('accuracy', 0.0)])
    classes = {'pos':1, 'neg':0}
    ## TO DO
    TP = FP = TN = FN = 0
    for result in results:
        class_label = result['class_label']
        prediction = result['prediction']
        true_label = class_label.index(max(class_label))
        pred_label = prediction.index(max(prediction))
        if true_label == 1 and pred_label == 1:
            TP += 1
        elif true_label == 0 and pred_label == 1:
            FP += 1
        elif true_label == 0 and pred_label == 0:
            TN += 1
        elif true_label == 1 and pred_label == 0:
            FN += 1

    
    accuracy['accuracy'] = (TP + TN) / (TP + FP + TN + FN)
    accuracy['precision'] = TP / (TP + FP) 
    accuracy['recall'] = TP / (TP + FN) 
    accuracy['f1'] = 2 * TP / (2 * TP + FP + FN) 
    ##
    return accuracy

Comparons maintenant les resultats de nos trois classificateurs N-grammes.

In [23]:
accuracies = {'unigram':get_accuracy_scores(unigram_results),
                  'bigram':get_accuracy_scores(bigram_results),
                  'trigram':get_accuracy_scores(trigram_results)}

In [24]:
pd.DataFrame.from_dict(accuracies, orient='index')

         precision  recall        f1  accuracy
unigram   0.890547   0.895  0.892768    0.8925
bigram    0.895833   0.860  0.877551    0.8800
trigram   0.839080   0.730  0.780749    0.7950

## Classificateur 2 : Classificateur basé sur un LSTM

Nous allons entraîner un classificateur basé sur un LSTM en utilisant l’état final de sortie du LSTM comme caractéristiques pour la classification des critiques.

8. **[3 points]** Écrivez une fonction utilitaire qui retourne le vocabulaire de tokens, *vocab*, étant donné un jeu de données de *tokenized_reviews* étiquetées (une liste de tuples *(tokenized_review, review_class)*). Il est important que la taille du vocabulaire soit limitée à *max_vocab_size*. *vocab* doit inclure les *max_vocab_size* tokens uniques les plus fréquents sur l’ensemble des critiques. Le type de retour sera différent du problème 2 : cette fois, *vocab* doit être un dictionnaire où les clés sont les types de tokens et les valeurs sont leurs indices, ordonnés par fréquence. Notez que les deux premiers éléments du dictionnaire *vocab* sont les tokens spéciaux '\[PAD\]' pour le remplissage (padding) du texte et '\[UNK\]' pour les mots inconnus, qui ont respectivement les indices réservés 0 et 1. Ainsi, l’indice du token le plus fréquent doit commencer à 2.

In [25]:
def get_vocabulary_maxsize(tokenized_reviews:list[tuple[list[str], str]], max_vocab_size:int):
    vocab = dict([('[PAD]', 0), ('[UNK]',1)])
    ## TO DO
    ### Construire token de l'ensemble des mots de toutes les critiques
    tokensOfEachReview=list(zip(*tokenized_reviews))[0]
    tokens = [token for review in tokensOfEachReview for token in review]
    ### Faire le compte des mots sur l'ensemble des critiques
    tokensCounter = Counter(tokens)
    ### Le Top-N définit le nouveau vocabulaire.
    tokensCounter = tokensCounter.most_common(max_vocab_size)
    vocab.update({token: idx+2 for idx, (token, _) in enumerate(tokensCounter)})

    
    ##
    return vocab

In [26]:
# TODO: à supprimer avant de soumettre
# Pour tester la fonction get_vocabulary_maxsize
get_vocabulary_maxsize(tokenized_reviews, 10000)

{'[PAD]': 0,
 '[UNK]': 1,
 'the': 2,
 'a': 3,
 'and': 4,
 'of': 5,
 'to': 6,
 'is': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'as': 11,
 'with': 12,
 'for': 13,
 'his': 14,
 'this': 15,
 'film': 16,
 'but': 17,
 'he': 18,
 'i': 19,
 'on': 20,
 'are': 21,
 'by': 22,
 'be': 23,
 'its': 24,
 'an': 25,
 'not': 26,
 'one': 27,
 'who': 28,
 'movie': 29,
 'at': 30,
 'was': 31,
 'from': 32,
 'have': 33,
 'has': 34,
 'you': 35,
 'her': 36,
 'they': 37,
 'all': 38,
 'so': 39,
 'like': 40,
 'about': 41,
 'out': 42,
 'more': 43,
 'when': 44,
 'which': 45,
 'up': 46,
 'their': 47,
 'what': 48,
 'or': 49,
 'some': 50,
 'just': 51,
 'if': 52,
 'there': 53,
 'into': 54,
 'him': 55,
 'she': 56,
 'even': 57,
 'only': 58,
 'than': 59,
 'no': 60,
 'good': 61,
 'we': 62,
 'most': 63,
 'time': 64,
 'can': 65,
 'will': 66,
 'story': 67,
 'films': 68,
 'been': 69,
 'would': 70,
 'much': 71,
 'also': 72,
 'get': 73,
 'other': 74,
 'characters': 75,
 'do': 76,
 'very': 77,
 'character': 78,
 'them': 79,
 'two': 80,
 'after': 81,
 'first': 82,
 'see': 83,
 'well': 84,
 'way': 85,
 'because': 86,
 'does': 87,
 'really': 88,
 'make': 89,
 'any': 90,
 'had': 91,
 'too': 92,
 'while': 93,
 'little': 94,
 'how': 95,
 'life': 96,
 'plot': 97,
 'were': 98,
 'where': 99,
 'then': 100,
 'me': 101,
 'people': 102,
 'off': 103,
 'could': 104,
 'my': 105,
 'bad': 106,
 'movies': 107,
 'scene': 108,
 'best': 109,
 'never': 110,
 'these': 111,
 'over': 112,
 'being': 113,
 'new': 114,
 'doesnt': 115,
 'man': 116,
 'scenes': 117,
 'many': 118,
 'know': 119,
 'dont': 120,
 'such': 121,
 'through': 122,
 'hes': 123,
 'another': 124,
 'great': 125,
 'here': 126,
 'action': 127,
 'go': 128,
 'love': 129,
 'end': 130,
 'director': 131,
 'us': 132,
 'back': 133,
 'something': 134,
 'still': 135,
 'seems': 136,
 'theres': 137,
 'work': 138,
 'those': 139,
 'made': 140,
 'now': 141,
 'however': 142,
 'world': 143,
 'makes': 144,
 'big': 145,
 'years': 146,
 'before': 147,
 'every': 148,
 'few': 149,
 'though': 150,
 'between': 151,
 'better': 152,
 'enough': 153,
 'both': 154,
 'seen': 155,
 'real': 156,
 'around': 157,
 'performance': 158,
 'down': 159,
 'audience': 160,
 'take': 161,
 'going': 162,
 'think': 163,
 'should': 164,
 'your': 165,
 'may': 166,
 'gets': 167,
 'role': 168,
 'why': 169,
 'things': 170,
 'same': 171,
 'actually': 172,
 'isnt': 173,
 'almost': 174,
 'last': 175,
 'look': 176,
 'own': 177,
 'thing': 178,
 'thats': 179,
 'nothing': 180,
 'although': 181,
 'funny': 182,
 'comedy': 183,
 'script': 184,
 'right': 185,
 'say': 186,
 'find': 187,
 'did': 188,
 'since': 189,
 'fact': 190,
 'played': 191,
 'cast': 192,
 'plays': 193,
 'come': 194,
 'old': 195,
 'long': 196,
 'john': 197,
 'ever': 198,
 'young': 199,
 'show': 200,
 'comes': 201,
 'part': 202,
 'without': 203,
 'actors': 204,
 'least': 205,
 'each': 206,
 'acting': 207,
 'lot': 208,
 'again': 209,
 'star': 210,
 'point': 211,
 'himself': 212,
 'original': 213,
 'away': 214,
 'course': 215,
 'takes': 216,
 'goes': 217,
 'during': 218,
 'quite': 219,
 'family': 220,
 'must': 221,
 'minutes': 222,
 'interesting': 223,
 'might': 224,
 'anything': 225,
 'rather': 226,
 'im': 227,
 'cant': 228,
 'guy': 229,
 'screen': 230,
 'three': 231,
 'effects': 232,
 'far': 233,
 'day': 234,
 'place': 235,
 'our': 236,
 'year': 237,
 'yet': 238,
 'didnt': 239,
 'once': 240,
 'watch': 241,
 'seem': 242,
 'fun': 243,
 'home': 244,
 'having': 245,
 'special': 246,
 'picture': 247,
 'kind': 248,
 'times': 249,
 'instead': 250,
 'trying': 251,
 'always': 252,
 'making': 253,
 'series': 254,
 'give': 255,
 'want': 256,
 'job': 257,
 'sense': 258,
 'wife': 259,
 'american': 260,
 'pretty': 261,
 'bit': 262,
 'along': 263,
 'help': 264,
 'becomes': 265,
 'men': 266,
 'probably': 267,
 'together': 268,
 'woman': 269,
 'set': 270,
 'become': 271,
 'actor': 272,
 'money': 273,
 'whole': 274,
 'black': 275,
 'hollywood': 276,
 'given': 277,
 'sure': 278,
 'hard': 279,
 'everything': 280,
 'gives': 281,
 'high': 282,
 'dialogue': 283,
 'watching': 284,
 'wants': 285,
 'music': 286,
 'feel': 287,
 'death': 288,
 'got': 289,
 'done': 290,
 'perhaps': 291,
 'sex': 292,
 'until': 293,
 'less': 294,
 'looks': 295,
 'next': 296,
 'everyone': 297,
 'play': 298,
 'moments': 299,
 'especially': 300,
 'james': 301,
 'different': 302,
 'theyre': 303,
 'father': 304,
 'rest': 305,
 'shows': 306,
 'whose': 307,
 'case': 308,
 'reason': 309,
 'anyone': 310,
 'simply': 311,
 'couple': 312,
 'completely': 313,
 'several': 314,
 'performances': 315,
 '2': 316,
 'left': 317,
 's': 318,
 'mind': 319,
 'looking': 320,
 'put': 321,
 'lost': 322,
 'horror': 323,
 'alien': 324,
 'itself': 325,
 'problem': 326,
 'shes': 327,
 'friends': 328,
 'girl': 329,
 'city': 330,
 'human': 331,
 'ive': 332,
 'main': 333,
 'humor': 334,
 'getting': 335,
 'ending': 336,
 'michael': 337,
 'turns': 338,
 'small': 339,
 'true': 340,
 'entire': 341,
 'line': 342,
 'evil': 343,
 'thought': 344,
 'either': 345,
 'certainly': 346,
 'final': 347,
 'mother': 348,
 'night': 349,
 'stars': 350,
 'use': 351,
 'against': 352,
 'someone': 353,
 'comic': 354,
 'half': 355,
 'later': 356,
 'found': 357,
 'sequence': 358,
 'begins': 359,
 'else': 360,
 'dead': 361,
 'based': 362,
 'school': 363,
 'wrong': 364,
 'idea': 365,
 'believe': 366,
 'playing': 367,
 'soon': 368,
 'town': 369,
 'keep': 370,
 'unfortunately': 371,
 'name': 372,
 'said': 373,
 'called': 374,
 'second': 375,
 'friend': 376,
 'tries': 377,
 'relationship': 378,
 'war': 379,
 'group': 380,
 'often': 381,
 'david': 382,
 'under': 383,
 'named': 384,
 'works': 385,
 'behind': 386,
 'finally': 387,
 'game': 388,
 'used': 389,
 'kids': 390,
 'tell': 391,
 'written': 392,
 'maybe': 393,
 'despite': 394,
 'perfect': 395,
 'able': 396,
 'youre': 397,
 'nice': 398,
 'doing': 399,
 'finds': 400,
 'fight': 401,
 'seeing': 402,
 'past': 403,
 'house': 404,
 'turn': 405,
 'mr': 406,
 'including': 407,
 'head': 408,
 'hand': 409,
 'running': 410,
 'book': 411,
 'run': 412,
 'side': 413,
 'shot': 414,
 'car': 415,
 'supposed': 416,
 'days': 417,
 'face': 418,
 'style': 419,
 'tv': 420,
 'camera': 421,
 'boy': 422,
 'joe': 423,
 'dark': 424,
 'directed': 425,
 'person': 426,
 'need': 427,
 'son': 428,
 'hour': 429,
 'live': 430,
 'example': 431,
 'daughter': 432,
 'worth': 433,
 'start': 434,
 'care': 435,
 'direction': 436,
 'lines': 437,
 'starts': 438,
 'others': 439,
 'entertaining': 440,
 'lives': 441,
 'review': 442,
 'kevin': 443,
 'upon': 444,
 'wasnt': 445,
 'moment': 446,
 'video': 447,
 'opening': 448,
 'major': 449,
 'worst': 450,
 'nearly': 451,
 'beautiful': 452,
 'sequences': 453,
 'version': 454,
 'matter': 455,
 'eyes': 456,
 'production': 457,
 'team': 458,
 'try': 459,
 'already': 460,
 'knows': 461,
 'summer': 462,
 'violence': 463,
 'early': 464,
 'guys': 465,
 'children': 466,
 'short': 467,
 'full': 468,
 'classic': 469,
 'order': 470,
 'fine': 471,
 'exactly': 472,
 'boring': 473,
 'jack': 474,
 'throughout': 475,
 'whos': 476,
 'screenplay': 477,
 'let': 478,
 'title': 479,
 'kill': 480,
 'act': 481,
 'hit': 482,
 'problems': 483,
 'obvious': 484,
 'top': 485,
 'question': 486,
 'beginning': 487,
 'truly': 488,
 'themselves': 489,
 'deep': 490,
 'space': 491,
 'simple': 492,
 'scream': 493,
 'women': 494,
 'sort': 495,
 'jackie': 496,
 'save': 497,
 'drama': 498,
 'roles': 499,
 'white': 500,
 'supporting': 501,
 'body': 502,
 'known': 503,
 'earth': 504,
 'tom': 505,
 'novel': 506,
 'yes': 507,
 'hell': 508,
 'killer': 509,
 'peter': 510,
 'ends': 511,
 'saw': 512,
 'worse': 513,
 'hope': 514,
 'room': 515,
 'wont': 516,
 'dog': 517,
 'van': 518,
 'sometimes': 519,
 'happens': 520,
 'genre': 521,
 'robert': 522,
 'ship': 523,
 'murder': 524,
 'lead': 525,
 'stupid': 526,
 'heart': 527,
 'extremely': 528,
 'strong': 529,
 'thriller': 530,
 'wonder': 531,
 'arent': 532,
 'planet': 533,
 'attempt': 534,
 'coming': 535,
 'five': 536,
 'particularly': 537,
 'appears': 538,
 'tells': 539,
 'manages': 540,
 'four': 541,
 'hero': 542,
 'jokes': 543,
 'quickly': 544,
 'says': 545,
 'police': 546,
 'voice': 547,
 'york': 548,
 'whats': 549,
 'sound': 550,
 'stop': 551,
 'involved': 552,
 'eventually': 553,
 'sets': 554,
 'taking': 555,
 'wild': 556,
 'aliens': 557,
 'among': 558,
 'involving': 559,
 'possible': 560,
 'result': 561,
 'level': 562,
 'close': 563,
 'future': 564,
 'late': 565,
 'emotional': 566,
 'fiction': 567,
 'alone': 568,
 'ones': 569,
 'material': 570,
 'bring': 571,
 'child': 572,
 'living': 573,
 'mostly': 574,
 'girls': 575,
 'hours': 576,
 'attention': 577,
 'fall': 578,
 'computer': 579,
 'career': 580,
 'lee': 581,
 'de': 582,
 'experience': 583,
 'elements': 584,
 'battle': 585,
 'romantic': 586,
 'mean': 587,
 'fans': 588,
 'number': 589,
 'leads': 590,
 'piece': 591,
 'happen': 592,
 'obviously': 593,
 'george': 594,
 'theater': 595,
 'note': 596,
 'guess': 597,
 'features': 598,
 'chance': 599,
 'disney': 600,
 'needs': 601,
 'lack': 602,
 'taken': 603,
 '1': 604,
 'meet': 605,
 'television': 606,
 'falls': 607,
 'success': 608,
 'usually': 609,
 'enjoy': 610,
 'chris': 611,
 'feature': 612,
 'feels': 613,
 'leave': 614,
 'form': 615,
 'meets': 616,
 'talk': 617,
 'science': 618,
 'youll': 619,
 'interest': 620,
 'poor': 621,
 'brother': 622,
 'killed': 623,
 'god': 624,
 'dr': 625,
 'parents': 626,
 'across': 627,
 'williams': 628,
 'none': 629,
 'laugh': 630,
 'words': 631,
 'word': 632,
 'single': 633,
 'apparently': 634,
 'attempts': 635,
 'mission': 636,
 'expect': 637,
 'deal': 638,
 'husband': 639,
 'told': 640,
 'paul': 641,
 'crew': 642,
 'talent': 643,
 'impressive': 644,
 'premise': 645,
 'robin': 646,
 'tale': 647,
 'call': 648,
 'laughs': 649,
 'whether': 650,
 'batman': 651,
 'brothers': 652,
 'score': 653,
 'within': 654,
 'wonderful': 655,
 'surprise': 656,
 'history': 657,
 '3': 658,
 'release': 659,
 'reality': 660,
 'ben': 661,
 'serious': 662,
 'sequel': 663,
 'seemed': 664,
 'stuff': 665,
 'released': 666,
 'oh': 667,
 'filmmakers': 668,
 'middle': 669,
 'easy': 670,
 'difficult': 671,
 'feeling': 672,
 'somehow': 673,
 'cool': 674,
 'parts': 675,
 'oscar': 676,
 'except': 677,
 'went': 678,
 'ryan': 679,
 'easily': 680,
 'local': 681,
 'recent': 682,
 'king': 683,
 'basically': 684,
 'viewers': 685,
 'couldnt': 686,
 'surprisingly': 687,
 'whom': 688,
 'audiences': 689,
 'runs': 690,
 'ill': 691,
 'complete': 692,
 'happy': 693,
 'am': 694,
 'forced': 695,
 'power': 696,
 'events': 697,
 'turned': 698,
 'working': 699,
 'giving': 700,
 'brings': 701,
 'amazing': 702,
 'remember': 703,
 'certain': 704,
 'girlfriend': 705,
 'smith': 706,
 'effective': 707,
 'return': 708,
 'ago': 709,
 'youve': 710,
 'important': 711,
 'hilarious': 712,
 'credits': 713,
 'change': 714,
 'lets': 715,
 'strange': 716,
 'art': 717,
 'suspense': 718,
 'read': 719,
 'blood': 720,
 'using': 721,
 'entertainment': 722,
 'somewhat': 723,
 'figure': 724,
 'popular': 725,
 'business': 726,
 'beyond': 727,
 'brilliant': 728,
 'die': 729,
 'similar': 730,
 'writing': 731,
 'successful': 732,
 'familiar': 733,
 'latest': 734,
 'came': 735,
 'presence': 736,
 'giant': 737,
 'due': 738,
 'rock': 739,
 'crime': 740,
 'personal': 741,
 'decides': 742,
 'rich': 743,
 'anyway': 744,
 'william': 745,
 'nature': 746,
 'begin': 747,
 'wouldnt': 748,
 'mystery': 749,
 'means': 750,
 'type': 751,
 'kid': 752,
 'understand': 753,
 'leaving': 754,
 'ways': 755,
 'stories': 756,
 'myself': 757,
 'visual': 758,
 'absolutely': 759,
 'previous': 760,
 'intelligent': 761,
 'excellent': 762,
 'trek': 763,
 'cut': 764,
 'definitely': 765,
 'towards': 766,
 'sexual': 767,
 'starring': 768,
 'flick': 769,
 'light': 770,
 'create': 771,
 'felt': 772,
 'uses': 773,
 'perfectly': 774,
 'viewer': 775,
 'shots': 776,
 'third': 777,
 'following': 778,
 '4': 779,
 'nor': 780,
 'company': 781,
 'cinema': 782,
 'add': 783,
 'predictable': 784,
 'clear': 785,
 'dramatic': 786,
 'red': 787,
 'thinking': 788,
 'created': 789,
 'secret': 790,
 'doubt': 791,
 'water': 792,
 'office': 793,
 'talking': 794,
 'questions': 795,
 'learn': 796,
 'romance': 797,
 'project': 798,
 'potential': 799,
 'huge': 800,
 'sam': 801,
 'powerful': 802,
 'situation': 803,
 'gone': 804,
 'clever': 805,
 'jim': 806,
 'annoying': 807,
 'herself': 808,
 'quality': 809,
 'opens': 810,
 'age': 811,
 'leaves': 812,
 'heard': 813,
 'effect': 814,
 'harry': 815,
 'america': 816,
 'wedding': 817,
 'straight': 818,
 'sweet': 819,
 'writer': 820,
 'seriously': 821,
 'move': 822,
 'near': 823,
 'present': 824,
 'married': 825,
 'bill': 826,
 'merely': 827,
 'force': 828,
 'actress': 829,
 'happened': 830,
 'mark': 831,
 'enjoyable': 832,
 'unlike': 833,
 'large': 834,
 'former': 835,
 'usual': 836,
 'plan': 837,
 'animated': 838,
 'follows': 839,
 'mars': 840,
 'saying': 841,
 'directors': 842,
 'likely': 843,
 'country': 844,
 'prison': 845,
 'million': 846,
 'took': 847,
 'bunch': 848,
 'general': 849,
 'smart': 850,
 'slow': 851,
 'motion': 852,
 'agent': 853,
 'private': 854,
 'fails': 855,
 'murphy': 856,
 'jones': 857,
 'escape': 858,
 'realize': 859,
 'ultimately': 860,
 'dumb': 861,
 'id': 862,
 'cold': 863,
 'impossible': 864,
 'break': 865,
 'message': 866,
 'tim': 867,
 'solid': 868,
 'r': 869,
 'points': 870,
 'pay': 871,
 'villain': 872,
 'immediately': 873,
 'scary': 874,
 'moving': 875,
 'above': 876,
 'various': 877,
 'soundtrack': 878,
 'inside': 879,
 'subject': 880,
 'follow': 881,
 'trouble': 882,
 'decent': 883,
 'brought': 884,
 'party': 885,
 'political': 886,
 'bob': 887,
 'biggest': 888,
 'carter': 889,
 'wars': 890,
 'spend': 891,
 'chase': 892,
 'bond': 893,
 'mess': 894,
 'truth': 895,
 'overall': 896,
 'scott': 897,
 'studio': 898,
 'richard': 899,
 'effort': 900,
 'eye': 901,
 'members': 902,
 'filled': 903,
 'credit': 904,
 'focus': 905,
 'wait': 906,
 'musical': 907,
 'eddie': 908,
 'cop': 909,
 'appear': 910,
 '10': 911,
 'fan': 912,
 'rating': 913,
 'favorite': 914,
 'steve': 915,
 'spent': 916,
 'keeps': 917,
 'english': 918,
 'totally': 919,
 'silly': 920,
 'martin': 921,
 'slightly': 922,
 'stay': 923,
 'humans': 924,
 'critics': 925,
 'dream': 926,
 'drug': 927,
 'earlier': 928,
 'liked': 929,
 'box': 930,
 'actual': 931,
 'exciting': 932,
 'entirely': 933,
 'animation': 934,
 'moves': 935,
 'open': 936,
 'neither': 937,
 'lots': 938,
 'element': 939,
 'l': 940,
 'memorable': 941,
 'british': 942,
 'gun': 943,
 'control': 944,
 'army': 945,
 'talented': 946,
 'air': 947,
 'terrible': 948,
 'havent': 949,
 'approach': 950,
 'setting': 951,
 'fast': 952,
 'thinks': 953,
 'frank': 954,
 'offers': 955,
 'wish': 956,
 'brief': 957,
 'view': 958,
 'law': 959,
 'titanic': 960,
 'ask': 961,
 'showing': 962,
 'suddenly': 963,
 'list': 964,
 'aspect': 965,
 'sit': 966,
 'ideas': 967,
 'park': 968,
 'greatest': 969,
 'song': 970,
 'ten': 971,
 'government': 972,
 'ability': 973,
 'cinematography': 974,
 'teen': 975,
 'constantly': 976,
 'otherwise': 977,
 'cannot': 978,
 'society': 979,
 'max': 980,
 'gave': 981,
 'bruce': 982,
 'state': 983,
 'depth': 984,
 'particular': 985,
 'woody': 986,
 'hands': 987,
 'whatever': 988,
 'typical': 989,
 'west': 990,
 'wanted': 991,
 'expected': 992,
 'modern': 993,
 'u': 994,
 'chan': 995,
 'clearly': 996,
 'hear': 997,
 'boys': 998,
 'disaster': 999,
 ...}

9. **[3 points]** Écrivez une fonction utilitaire qui prend un dictionnaire de vocabulaire, *vocab*, et une critique tokenisée, *tokenized_review*, et qui retourne une *indexed_review*, où chaque token a été remplacé par son indice correspondant dans le dictionnaire *vocab*. Si un mot n’est pas présent dans le vocabulaire, il doit être remplacé par l’indice du token spécial '\[UNK\]'. Le type de retour doit être un torch tensor de int64.

In [27]:
def get_indexed_review(tokenized_review:list[str], vocab:dict[str,int]):
    indexed_review = torch.tensor([0], dtype=torch.long)
    ## TO DO
    tokenized_review_idx = [vocab.get(token, vocab['[UNK]']) for token in tokenized_review]
    indexed_review = torch.cat((indexed_review, torch.tensor(tokenized_review_idx, dtype=torch.long)), dim=0)
    
    
    ##
    return indexed_review

In [28]:
#TODO: à supprimer avant de soumettre
# Pour tester la fonction get_indexed_review
vocabTest = get_vocabulary_maxsize(tokenized_reviews, 50)
indexed_reviewTest = get_indexed_review(tokenized_reviews[random.randint(0, len(tokenized_reviews) - 1)][0], vocabTest)
indexed_reviewTest

tensor([ 0,  2,  1,  1,  1, 22,  1,  1,  7,  1, 27,  5,  2,  1,  1,  1,  1,  3,
         1,  1, 41,  2,  1,  5,  3,  1,  5,  1, 32,  3,  1,  1,  1,  1,  2,  1,
         1,  1,  6, 23, 27,  5,  1,  1,  9, 35,  1,  1,  1,  8, 15,  1,  1,  1,
        13,  1,  1,  5,  1,  1,  1, 21,  1,  8, 22, 38,  1,  4,  1,  1,  1,  1,
         2,  1,  1,  1,  2,  1,  1,  2,  1,  1,  5,  2, 16,  1,  1, 12, 25,  1,
         1,  1,  2,  1,  5,  3,  1,  5,  1, 32,  3,  1,  1, 28,  1,  4,  1, 42,
         1,  1,  1,  1, 22,  1,  1,  1,  7,  1,  1, 20, 11,  2,  1,  1,  5,  2,
         1,  1,  3,  1,  1,  2,  1,  1, 47,  1, 30,  3,  1,  6,  1,  1,  6,  2,
         1,  1,  1,  1,  1,  1,  1,  1,  5,  2,  1,  1,  1,  1,  1,  4,  1,  1,
         1,  1, 23,  1,  1, 13,  1, 17, 26,  1,  1,  1,  1,  1,  2,  1,  2,  1,
         1,  1,  1,  1,  1, 27,  1,  1, 20,  3,  1,  1, 27,  5, 47,  1,  1, 15,
         1,  5,  1,  1,  1,  6,  1,  2,  1,  5,  3,  1,  1,  5,  1, 28,  1, 23,
         1,  4,  1,  1, 22,  2,  1,  4,  1,  5,  1,  2,  1,  1,  1,  1, 22,  1,
        11,  1,  1,  1,  1,  1,  1, 43,  2,  1,  5,  2,  1,  1,  2,  1,  1, 22,
         1,  1,  1,  1,  1,  4,  1, 28,  1,  1,  1,  1,  2,  1,  5,  2, 29, 31,
         1,  1,  1,  6,  1,  1,  4,  1, 26,  6,  1,  8,  2,  1,  1,  2,  1,  1,
         5,  2, 29,  1, 12,  2,  1,  5,  1, 20,  2,  1,  1,  8,  1,  1,  8,  3,
         1,  1,  1,  1,  1, 22,  2,  1,  1,  2,  1, 21,  1,  1,  4,  1,  8,  3,
         1,  1, 20,  3,  1, 15,  1,  1, 22,  2,  1,  1,  1,  2,  1,  1,  8,  2,
        29,  1,  2,  1, 21,  1,  6,  1,  1,  1,  1,  1,  1,  1, 28,  7,  1,  1,
        22, 15,  1,  5,  1,  7,  1,  8,  3,  1,  1, 12,  1, 46,  6, 14,  1, 44,
        18,  1,  6,  1,  1,  1, 14,  1,  1, 22,  1,  1,  9,  2,  1,  1,  9,  1,
         1,  1,  7,  1,  2,  1,  1,  1,  1,  1,  1,  4,  1, 37,  1,  1, 12,  1,
         1,  8,  2,  1,  1, 19,  1,  9,  1,  1,  1,  1,  1,  1, 31,  1,  8,  3,
         1,  1,  8,  1,  4,  2,  1,  1,  2,  1, 21,  1,  1,  6,  1, 17, 21,  1,
         1,  7,  1,  6,  1,  1, 28,  1, 46,  1, 14,  1,  6,  1,  1,  1,  1,  1,
        14,  1,  6,  1,  4,  3,  1,  1,  1,  1,  1,  1,  1,  4,  1, 26,  1, 30,
        38, 40,  3,  1, 18,  1,  6,  1,  2,  1,  4,  1,  9, 14,  1,  1, 40,  6,
         1,  1,  1, 18,  1,  9,  1,  7,  1,  1,  8,  1,  2,  1,  1,  1, 43, 20,
         1,  1, 28,  1,  1,  1,  3,  1,  1,  1,  1,  2,  1,  7,  1,  1,  1,  1,
         8, 15,  1, 35,  1, 13,  1,  1, 34,  1,  9,  1,  7,  1,  1,  1,  4,  1,
         6,  1,  6,  1,  6,  1,  1,  2,  1,  1,  1,  1,  1, 30,  2,  1,  1,  1,
        17,  1, 26,  1, 46,  1,  1,  1,  1,  1,  8,  2,  1,  4,  1,  6,  1,  1,
         1,  3,  1,  1,  4, 13,  1,  3,  1,  1, 29,  2,  1,  1,  7,  3,  1,  1,
        29,  9,  1, 26, 23,  1,  2,  1,  1,  1, 21,  1,  8, 22, 38,  1,  4,  1,
         1, 45,  7,  1,  6, 23, 30, 14,  1,  1,  8, 15, 16,  7,  1,  1,  1, 26,
         1, 15, 16, 10,  1,  1,  4,  1, 35])

10. **[4 points]** Écrivez une classe *LSTMReviewDataset* qui implémente un objet *torch Dataset*. Elle doit prendre en entrée *tokenized_reviews* (une liste de tuples *(tokenized_review, review_class)*) ainsi qu’un dictionnaire de vocabulaire, *vocab*. Votre fonction d’initialisation doit transformer toutes les critiques tokenisées en séquences d’indices, de sorte que *self.indexed_reviews* soit une liste de torch tensor. Quant à *self.labels*, il doit également s’agir d’un torch tensor de taille |tokenized_reviews| × |review_classes|, où chaque élément est un vecteur one‑hot tel que [1,0] correspond à la classe « neg » et [0,1] à la classe « pos ».

In [34]:
class LSTMReviewDataset(Dataset):
    def __init__(self, tokenized_reviews:list[tuple[list[str], str]], vocab:dict[str,int]):
        indexed_reviews = [] 
        labels = [] 
        ## TO DO
        for tokenized_review, label in tokenized_reviews:
            indexed_reviews.append(get_indexed_review(tokenized_review, vocab))
            labels.append(0 if label == 'neg' else 1)
        
              
        ##
        self.indexed_reviews = indexed_reviews
        self.labels = F.one_hot(torch.Tensor(labels).long()).float()
        self.length = len(labels)

    def __getitem__(self, idx):
        ## TO DO
        indexed_review = self.indexed_reviews[idx]
        label = self.labels[idx]

        
        ##
        return indexed_review, label, idx

    def __len__(self):
        return self.length

11. **[3 points]** Écrivez une fonction *collate* personnalisée. Cette fonction sert à standardiser tous les éléments d’un lot. Elle peut être passée au *dataloader* comme paramètre. Comme chaque élément est une séquence d’indices représentant une critique, les séquences peuvent avoir des longueurs différentes. Afin de les regrouper dans un seul tenseur, nous devons standardiser leurs longueurs pour que toutes les séquences d’un lot aient la même longueur, égale à celle de la séquence la plus longue du lot. Nous ferons cela en remplissant les séquences avec des zéros — l’indice du token spécial '\[PAD\]' — au début de chaque séquence. Par exemple, si la longueur maximale d’un lot est 5 et que nous avons la séquence [22,300,6584], elle deviendra [0,0,22,300,6584]. Les sorties finales *batched_sequences* et *batched_labels* doivent être des torch tensor de type *long*, avec les dimensions |batch_size| × |taille maximale de séquence| et |batch_size| × |output_dim|, où *output_dim* correspond au nombre de classes. *batched_ids* vous est déjà fourni.

In [40]:
def collate_fn(items):
    sequences, labels, ids = list(zip(*items))
    batched_sequences = torch.tensor([0],dtype=torch.long)
    batched_labels = torch.tensor([0],dtype=torch.long)
    ##
    max_length = max([len(seq) for seq in sequences])
    padded_sequences = []
    for seq in sequences:
        nPads = max_length - len(seq)
        pads = torch.zeros(nPads, dtype=torch.long)
        padded_seq = torch.cat((pads, seq), dim=0)
        padded_sequences.append(padded_seq)
    batched_sequences = torch.stack(padded_sequences, dim=0)
    batched_labels = torch.stack(labels, dim=0)

    
    ##
    return batched_sequences, batched_labels, ids

In [43]:
# TODO: à supprimer avant de soumettre
# Pour tester la fonction collate_fn
tempDataset = LSTMReviewDataset(tokenized_reviews, get_vocabulary_maxsize(tokenized_reviews, 100))
tempDataLoader = DataLoader(tempDataset, batch_size=32, shuffle=True, collate_fn=collate_fn)
for batch_inputs, batch_labels, batch_ids in tempDataLoader:
    print(batch_inputs.shape, batch_labels.shape, len(batch_ids))
    break

torch.Size([32, 1326]) torch.Size([32, 2]) 32

12. **[2 points]** Écrivez une fonction *get_lstm_dataloader* qui prend en entrée *tokenized_reviews*, *vocab*, une taille de lot *batch_size*, un hyperparamètre *shuffle* et une fonction de *collate*. Elle doit utiliser la classe *LSTMReviewDataset* définie précédemment et retourner un objet de type *torch.utils.data.DataLoader* tenant compte des paramètres d’entrée.

In [47]:
def get_lstm_dataloader(tokenized_reviews:list[tuple[list[str], str]], vocab:dict[str,int], batch_size:int, shuffle:bool, collate_fn=collate_fn):
    ## TO DO
    data = LSTMReviewDataset(tokenized_reviews, vocab)
    dataloader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

    
    ##
    return dataloader

13. **[3 points]** Complétez la fonction *forward* de notre classificateur LSTM. Elle doit utiliser une boucle récurrente avec une cellule LSTM afin de produire des caractéristiques de classification basées sur le LSTM. N’utilisez que l’état caché final comme caractéristiques d’entrée pour la *final_classifier_layer*, qui sera un classificateur de régression logistique.

In [48]:
class LSTMClassifier(nn.Module):
    def __init__(self, vocab_size, emb_dim, hidden_dim, output_dim):
        super(LSTMClassifier, self).__init__()
        self.vocab_size = vocab_size
        self.emb_dim = emb_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.embeddings = nn.Embedding(self.vocab_size, self.emb_dim, padding_idx=0)
        self.lstm = nn.LSTMCell(self.emb_dim, self.hidden_dim)
        self.final_classifier_layer = LogisticRegression(self.hidden_dim, self.output_dim)

    def forward(self, input): # |batch_size| x |sequence_length| x |emb_dim|
        batch_size = input.size()[0]
        sequence_length = input.size()[1]
        #our initial h_(i-1) and c_(i-1) vectors are dummies
        h_prior = torch.zeros(batch_size, self.hidden_dim)
        c_prior = torch.zeros(batch_size, self.hidden_dim)
        ## TO DO
        input_t = torch.transpose(input, 0, 1) # |sequence_length| x |batch_size| x |emb_dim|
        for i in range(sequence_length):
            x_i = self.embeddings(input_t[i])
            h_prior, c_prior = self.lstm(x_i, (h_prior, c_prior))
        

         # Use the final hidden state for classification
        output = self.final_classifier_layer(h_prior)
        
        ##
        return output

#### Entraînons notre classificateur basé sur un LSTM !

L’entraînement du modèle prendra un certain temps — prévoyez environ 15 minutes sur un ordinateur portable de gamme moyenne.

In [49]:
def train_LR_lstm_classifier(train_dataset:list[tuple[str, str]], review_classes:list[str], batch_size = 32): 
    tokenized_train = [(preprocess(review), review_class) for review, review_class in  train_dataset]
    vocab = get_vocabulary_maxsize(tokenized_train, 10000)
    
    train_dataloader = get_lstm_dataloader(tokenized_train, vocab, batch_size, shuffle=True)

    model = LSTMClassifier(len(vocab), 64, 64, len(review_classes))
    trained_model = train(model, train_dataloader)
    return vocab, trained_model

In [50]:
lstm_vocab, lstm_model = train_LR_lstm_classifier(train_dataset, review_classes)

Epoch 1:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 2:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 3:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 4:   0%|          | 0/50 [00:00<?, ?it/s]

Epoch 5:   0%|          | 0/50 [00:00<?, ?it/s]

Nous pouvons évaluer notre classificateur basé sur un LSTM à l’aide de la même fonction *eval()* définie précédemment. Nous l’évaluerons à la fois sur les données de test et d’entraînement afin de comparer les performances du modèle.

In [29]:
def eval_LR_lstm_classifier(test_dataset:list[tuple[str, str]], lstm_vocab:list[tuple], model, collate_fn=collate_fn):
    tokenized_test = [(preprocess(review), review_class) for review, review_class in  test_dataset]
    test_dataloader = get_lstm_dataloader(tokenized_test, lstm_vocab, batch_size=32, shuffle=False, collate_fn=collate_fn)
    results = eval(model, test_dataloader)
    return results

In [30]:
lstm_test_results = eval_LR_lstm_classifier(test_dataset, lstm_vocab, lstm_model)
lstm_train_results = eval_LR_lstm_classifier(train_dataset, lstm_vocab, lstm_model)
lstm_accuracies = {'lstm test':get_accuracy_scores(lstm_test_results),
                  'lstm train':get_accuracy_scores(lstm_train_results)}
pd.DataFrame.from_dict(lstm_accuracies, orient='index')

            precision   recall        f1  accuracy
lstm test    0.623529  0.53000  0.572973   0.60500
lstm train   0.911517  0.81125  0.858466   0.86625

In [ ]:
#Que remarquez-vous concernant la relation entre la précision, le rappel et le score F1 dans cette tâche ? Pourquoi cela pourrait-il être le cas ? Écrivez 1 ou 2 phrases expliquant votre observation.
# Les métriques précision, rappel et F1 sont toutes relativement élevées et proches les unes des autres, ce qui suggère que le modèle a un bon équilibre entre la précision et le rappel. Cela pourrait être dû au fait que les critiques de films ont des caractéristiques distinctes qui permettent au modèle de les différencier efficacement, ou que le modèle a été bien entraîné pour capturer les nuances du langage utilisé dans les critiques.

## Questions bonus

14. **[1 point bonus]** Que remarquez-vous concernant la relation entre la précision, le rappel et le score F1 dans cette tâche ? Pourquoi cela pourrait-il être le cas ? Écrivez 1 ou 2 phrases expliquant votre observation.

In [ ]:
#Les métriques d'entraînement sont meilleures que les métriques de test, ce qui suggère que le modèle a peut-être surappris les données d'entraînement. Cependant, les métriques de test ne sont pas catastrophiques, ce qui indique que le modèle a tout de même appris des représentations utiles pour la classification.
#Toutes les métriques ont des valeurs de précision, rappel, F1 et accuracy similaires, ce qui suggère que le modèle a un bon équilibre entre la précision et le rappel, et qu'il est globalement performant pour la classification des critiques de films.

Les métriques ont des valeurs similaires.

15. **[1 point bonus]** Qu’observez-vous à propos des résultats du LSTM ? Selon vous, à quel point ce modèle serait-il performant pour classifier de nouvelles critiques du monde réel comparativement, par exemple, au classificateur bigramme ? Écrivez 2 à 3 phrases expliquant vos observations et votre hypothèse concernant la performance du modèle sur des données nouvelles et inédites.